.\" Man page for pig program for lab 5 of csci 241
.\" Thomas Nemeh and Lukas Griffin - Fall 2018

.TH pig_manpage 1 "31 October 2018" "CSCI 241" "Oberlin College"

.SH NAME
.B pig_manpage
\- manpage for pig

.SH SYNOPSIS
.B ./pig [-h | -?]

.SH DESCRIPTION
pig is a program that reads English text from stdin and outputs text converted to Pig Latin.

.SH OPTIONS
.IP "-h"
Prints out brief usage message and exits the program with a non-zero value
.IP "-?"
Prints out brief usage message and exits the program with a non-zero value

.SH AUTHOR
Thomas Nemeh and Lukas Griffin(Fall 2018)

.SH BUGS
None!
